[build]
# Set the Java home directly in the build command
command = "./gradlew -Dorg.gradle.java.home=$JAVA_HOME jsBrowserDistribution --no-daemon"

# Directory to publish
publish = "composeApp/build/dist/js/productionExecutable/"

[build.environment]
# This sets the $JAVA_HOME variable that the command will use
JAVA_VERSION = "17"