[build]
# Command to run
command = "./gradlew jsBrowserDistribution"

# Directory to publish
publish = "composeApp/build/dist/js/productionExecutable/"

[build.environment]
# Force the build to use Java 17
JAVA_VERSION = "17"