[build]
command = "./gradlew jsBrowserDistribution"
publish = "composeApp/build/dist/js/productionExecutable/"

[build.environment]
# We still need this to avoid Node 22+ issues
NODE_VERSION = "18"
# We REMOVE the JAVA_HOME variable
# The Aptfile will install Java 17, and the
# build environment should find it automatically.